name: update car software

on:
  push:
    branches: ["main"]

jobs:
  update_car_sw:
    runs-on: carpi-4
    steps:
      - name: pull latest image
        run: docker pull shifi23/car-interface:latest
      - name: stop running containers
        run: docker stop $(docker ps -a -q)
      - name: start new container
        run: docker run -d -p 8000:8000 --privileged shifi23/car-interface:latest
